/**
 * 日本語ジャンルラベル → FANZA DB の実ジャンルタグ のマッピング。
 * VideoFeed（クライアント側フィルタ）と api/feed/route.ts（サーバー側フィルタ）
 * の両方がここから import する。
 */
export const GENRE_MAP: Record<string, string[]> = {
  // ---- タイプ ----
  "ギャル": ["promiscuous", "hardcore"],
  "可愛い": ["bishoujo", "beautiful-style", "idol-celebrity", "cute"],
  "クール": ["cool", "beautiful-style"],
  "セクシー": ["seductress", "sexy"],
  "清楚": ["innocent", "beautiful-style"],
  "グラマラス": ["seductress", "huge-breasts", "beautiful-style"],
  "スレンダー": ["slender"],
  "グラマー": ["big-breasts"],
  "小柄": ["petite", "mini"],
  "長身": ["tall"],
  "アスリート": ["athlete", "muscular"],
  "筋肉": ["muscular", "athlete"],
  "ぽっちゃり": ["chubby"],
  "巨乳": ["big-breasts", "huge-breasts", "big-breasts-fetish"],
  "微乳・貧乳": ["small-breasts"],
  "超乳": ["huge-breasts", "big-breasts"],
  "巨尻": ["big-butt", "butt-fetish"],
  "むっちり": ["chubby", "big-butt"],
  "大人っぽい": ["mature-mother", "seductress"],
  "お姉さん": ["oneesan"],
  "モデル系": ["beautiful-style"],
  "アジア系": [],
  "欧美系": [],
  "巨乳フェチ": ["big-breasts-fetish"],
  "尻フェチ": ["butt-fetish"],
  "パイパン": ["shaved"],
  "ミニ系": ["mini", "petite"],
  "主観": ["pov"],
  "汗だく": ["sweaty"],
  "美少女": ["bishoujo", "beautiful-style"],
  "その他（タイプ）": ["other"],
  "色白": ["fair-skin"],
  "清潔": ["innocent"],
  "美乳": ["beautiful-style", "big-breasts"],

  // ---- コスチューム ----
  "コスプレ": ["cosplay"],
  "制服": ["uniform", "student-uniform-adult"],
  "セーラー服": ["sailor-uniform"],
  "水着": ["swimsuit"],
  "競泳・スクール水着": ["school-swimsuit"],
  "ボディコン": ["bodycon"],
  "ランジェリー": ["lingerie"],
  "エプロン": ["apron", "naked-apron"],
  "裸エプロン": ["naked-apron"],
  "バニー": ["bunny"],
  "覆面・マスク": ["mask"],
  "めがね": ["glasses"],
  "パンスト・タイツ": ["pantyhose"],
  "ニーソックス": ["knee-socks"],
  "レオタード": ["leotard"],
  "和服・浴衣": ["kimono"],
  "体操着": ["gym-uniform", "bloomers"],
  "ビジネススーツ": ["business-suit", "office-mix"],
  "その他（コス）": ["other"],
  "学生服": ["student-adult", "school-adult", "student-uniform-adult"],
  "秘書": ["secretary"],
  "女装・男の娘": ["crossdress"],
  "チャイナドレス": ["china-dress"],
  "ルーズソックス": ["loose-socks"],
  "レースクィーン": ["race-queen"],
  "チアガール": ["cheerleader"],
  "ブルマ": ["bloomers"],
  "スチュワーデス": ["stewardess", "cabin-attendant"],

  // ---- ジャンル ----
  "コラボ作品": ["collab"],
  "ベスト・総集編": ["best-compilation"],
  "デビュー作品": ["debut"],
  "単体作品": ["solo"],
  "SF": ["sf"],
  "イメージビデオ": ["image-video"],
  "イメージビデオ（男性）": ["image-video"],
  "フェチ": ["fetish"],
  "脚・足フェチ": ["leg-foot-fetish"],
  "ドキュメント系": ["documentary"],
  "素人": ["amateur"],
  "企画": ["planning"],
  "その他フェチ": ["other-fetish"],
  "その他（ジャンル）": ["other"],
  "アクション": ["action"],
  "アニメ": ["anime"],
  "クラシック": ["classic"],
  "SM": ["sm", "hardcore"],
  "ギャグ・コメディ": ["gag-comedy"],
  "学園もの": ["school-adult", "student-adult"],
  "恋愛": ["romance"],
  "痴女": ["seductress", "promiscuous"],
  "淫語": ["obscene-talk", "dirty-talk"],
  "ハーレム": ["harem"],
  "童貞": ["virgin-theme"],
  "辱め": ["humiliation", "humiliation-strong"],
  "近親相姦": ["incest-taboo"],
  "イタズラ": ["prank"],
  "ドラマ": ["story-drama"],
  "寝取り・寝取られ・NTR": ["ntr"],
  "乱行": ["multiple-play", "4p", "3p"],
  "淫乱": ["promiscuous", "hardcore"],
  "淫乱・ハード系": ["hardcore", "promiscuous"],
  "レズビアン": ["lesbian"],
  "ナンパ": ["pickup"],
  "即ハメ": ["instant"],
  "不倫": ["affair"],
  "BL（ボーイズラブ）": [],
  "オタク": ["otaku"],
  "お姫様": ["princess"],
  "ギリモザ": ["giri-mosaic"],
  "コンパニオン": ["companion"],
  "セレブ": ["celebrity"],
  "盗撮・のぞき": ["voyeur"],
  "複数話": ["multiple-episodes"],
  "放置": ["hands-off", "neglect"],
  "ビッチ": ["bitch"],
  "触手": ["tentacle"],
  "時間停止": ["time-stop"],

  // ---- 職業・属性 ----
  "アイドル・芸能人": ["idol-celebrity", "celebrity"],
  "オフィス": ["office-mix", "office"],
  "上司": ["boss"],
  "部下・同僚": ["subordinate-colleague"],
  "面接": ["interview"],
  "医者": ["hospital-clinic"],
  "看護師": ["nurse"],
  "教師": ["teacher", "teacher-adult"],
  "インストラクター": ["instructor"],
  "ウェイトレス": ["waitress"],
  "メイド": ["maid"],
  "CA・スチュワーデス": ["stewardess", "cabin-attendant"],
  "受付嬢": ["receptionist"],
  "マッサージ": ["massage", "massage-play"],
  "エステ": ["esthetic"],
  "病院・クリニック": ["hospital-clinic"],
  "ホテル": ["hotel"],
  "温泉": ["hot-spring"],
  "お風呂": ["bath"],
  "自宅": ["home"],
  "野外・屋外": ["outdoor"],
  "旅行": ["travel"],
  "デート": ["date"],
  "飲み会・合コン": ["drinking-party"],
  "近所・ご近所": [],
  "カップル": ["couple"],
  "人妻": ["married-woman", "housewife"],
  "熟女": ["milf", "mature-mother"],
  "ママ友": ["mom-friend"],
  "姉・妹": ["sisters"],
  "キャバ嬢・風俗嬢": ["hostess-service"],
  "主婦": ["housewife", "married-woman"],
  "義母": ["stepmother"],
  "女教師": ["teacher", "teacher-adult"],
  "OL・職業色々": ["office-mix", "business-suit"],
  "女子大生": ["college-student"],
  "お母さん": ["mature-mother"],
  "女子校生": ["student-adult", "school-adult"],

  // ---- プレイ ----
  "キス": ["kiss"],
  "マッサージプレイ": ["massage-play"],
  "ロールプレイ": ["cosplay"],
  "おもちゃ": ["toys", "electric-toy"],
  "コスプレプレイ": ["cosplay"],
  "3P": ["3p"],
  "複数プレイ": ["multiple-play", "4p"],
  "シャワー": ["shower", "bath"],
  "ローション": ["lotion"],
  "オイル": ["oil-play"],
  "焦らし": ["tease"],
  "言葉責め": ["obscene-talk", "dirty-talk"],
  "フェラ": ["blowjob"],
  "パイズリ": ["titjob"],
  "手コキ": ["handjob"],
  "クンニ": ["cunnilingus"],
  "オナニー": ["masturbation"],
  "シックスナイン": ["sixty-nine"],
  "アナルセックス": ["anal-sex"],
  "イマラチオ": ["iramachio"],
  "イラマチオ": ["irrumatio", "iramachio"],
  "中出し": ["creampie"],
  "顔射": ["facial"],
  "縛り・緊縛": ["bondage", "restraint"],
  "騎乗位": ["cowgirl"],
  "潮吹き": ["squirting"],
  "放尿・お漏らし": ["urination"],
  "飲尿": ["drink-urine"],
  "羞恥": ["humiliation"],
  "羞め": ["humiliation-strong"],
  "4P": ["4p"],
  "デカチン・巨根": ["big-dick"],
  "その他（プレイ）": ["other-fetish"],
  "電マ": ["electric-toy"],
  "拘束": ["restraint", "bondage"],
  "ぶっかけ": ["finish"],
  "パンチラ": ["panty-shot"],
  "胸チラ": ["boob-slip"],
  "スパンキング": ["spanking"],
  "カーセックス": ["car-sex"],
  "スカトロ": ["scat"],
  "ヨガ": ["yoga"],
  "オナサポ": ["support-masturbation"],

  // ---- その他 ----
  "VR": ["vr", "vr-only"],
  "ハイクオリティVR": ["high-quality-vr"],
  "スマホ推奨": [],
  "短尺": [],
  "4時間以上": ["over-4-hours"],
  "16時間以上": ["over-16-hours"],
  "シリーズ": ["set"],
  "セット商品": ["set"],
  "デジモ": ["digimo"],
  "独占配信": ["exclusive"],
  "AI生成作品": ["ai-generated"],
  "FANZA配信限定": ["fanza-exclusive"],
  "4K": ["4k"],
  "3D": ["3d"],
  "その他": ["other"],
  "VR専用": ["vr-only"],
  "縦動画": [],
};
