// ===== src/lib/genreMap.ts =====
export const GENRE_MAP: Record<string, string[]> = {
  // ---- タイプ ----
  "ギャル": ["gal", "gyaru"],
  "可愛い": ["cute", "kawaii"],
  "クール": ["cool"],
  "セクシー": ["sexy"],
  "清楚": ["innocent", "pure", "seiso"],
  "グラマラス": ["glamorous"],
  "スレンダー": ["slender", "thin"],
  "グラマー": ["glamour", "glamorous"],
  "小柄": ["petite", "small", "tiny"],
  "長身": ["tall", "long-legs"],
  "アスリート": ["athlete", "athletic"],
  "筋肉": ["muscle", "muscular"],
  "ぽっちゃり": ["chubby", "plump"],
  "巨乳": ["big-breasts", "large-breasts", "boobs"],
  "微乳・貧乳": ["small-breasts", "flat", "poor-breasts"],
  "超乳": ["huge-breasts", "super-breasts", "ultra-breasts"],
  "巨尻": ["big-ass", "big-butt", "large-hips"],
  "むっちり": ["thick", "curvy", "voluptuous"],
  "大人っぽい": ["mature", "adult"],
  "お姉さん": ["older-sister", "oneesan"],
  "モデル系": ["model"],
  "アジア系": ["asian"],
  "欧美系": ["western", "european", "american"],
  "巨乳フェチ": ["big-breasts-fetish"],
  "尻フェチ": ["ass-fetish", "butt-fetish"],
  "パイパン": ["shaved", "hairless", "no-hair"],
  "ミニ系": ["mini", "small-type"],
  "主観": ["pov", "subjective"],
  "汗だく": ["sweaty", "sweat"],
  "美少女": ["bishoujo", "beautiful-girl"],
  "色白": ["fair-skin", "white-skin"],
  "清潔": ["clean", "hygienic"],
  "美乳": ["beautiful-breasts"],

  // ---- コスチューム ----
  "コスプレ": ["cosplay"],
  "制服": ["uniform"],
  "セーラー服": ["sailor-uniform", "sailor-suit"],
  "水着": ["swimsuit"],
  "競泳・スクール水着": ["school-swimsuit", "competition-swimsuit"],
  "ボディコン": ["bodycon"],
  "ランジェリー": ["lingerie"],
  "エプロン": ["apron"],
  "裸エプロン": ["naked-apron"],
  "バニー": ["bunny", "bunny-girl"],
  "覆面・マスク": ["mask", "masked"],
  "めがね": ["glasses"],
  "パンスト・タイツ": ["pantyhose", "tights"],
  "ニーソックス": ["knee-socks"],
  "レオタード": ["leotard"],
  "和服・浴衣": ["kimono", "yukata", "japanese-clothes"],
  "体操着": ["gym-uniform"],
  "ビジネススーツ": ["business-suit", "suit"],
  "学生服": ["student-uniform"],
  "秘書": ["secretary"],
  "女装・男の娘": ["crossdressing", "otokonoko", "shemale"],
  "チャイナドレス": ["china-dress", "cheongsam"],
  "ルーズソックス": ["loose-socks"],
  "レースクィーン": ["race-queen"],
  "チアガール": ["cheerleader"],
  "ブルマ": ["bloomer"],
  "スチュワーデス": ["stewardess", "flight-attendant"],

  // ---- 作品/ジャンル ----
  "コラボ作品": ["collab", "collaboration"],
  "ベスト・総集編": ["best", "compilation", "omnibus"],
  "デビュー作品": ["debut"],
  "単体作品": ["solo"],
  "SF": ["sf", "sci-fi"],
  "イメージビデオ": ["image-video"],
  "イメージビデオ（男性）": ["image-video-male"],
  "フェチ": ["fetish"],
  "脚・足フェチ": ["leg-fetish", "foot-fetish"],
  "ドキュメント系": ["documentary"],
  "素人": ["amateur"],
  "企画": ["planning", "project"],
  "アクション": ["action"],
  "アニメ": ["anime"],
  "クラシック": ["classic"],
  "SM": ["sm", "bdsm"],
  "ギャグ・コメディ": ["comedy", "gag"],
  "学園もの": ["school", "campus"],
  "恋愛": ["love", "romance"],
  "痴女": ["slut", "nympho", "chijo"],
  "淫語": ["dirty-talk"],
  "ハーレム": ["harem"],
  "童貞": ["virgin"],
  "辱め": ["humiliation"],
  "近親相姦": ["incest"],
  "イタズラ": ["prank", "mischief"],
  "ドラマ": ["drama"],
  "寝取り・寝取られ・NTR": ["ntr", "netorare", "cuckold"],
  "乱行": ["orgy", "group-sex"],
  "淫乱": ["nympho", "lewd"],
  "淫乱・ハード系": ["hard", "hardcore"],
  "レズビアン": ["lesbian"],
  "ナンパ": ["pick-up"],
  "即ハメ": ["instant-sex", "quickie"],
  "不倫": ["affair", "adultery"],
  "BL（ボーイズラブ）": ["bl", "boys-love"],
  "オタク": ["otaku"],
  "お姫様": ["princess"],
  "ギリモザ": ["mosaic", "barely-mosaic"],
  "コンパニオン": ["companion"],
  "セレブ": ["celebrity"],
  "盗撮・のぞき": ["voyeur", "hidden-camera", "peeping"],
  "複数話": ["multi-episode", "episodes"],
  "放置": ["neglect", "abandon"],
  "ビッチ": ["bitch"],
  "触手": ["tentacle"],
  "時間停止": ["time-stop"],

  // ---- 職業いろいろ ----
  "アイドル・芸能人": ["idol", "celebrity"],
  "オフィス": ["office"],
  "上司": ["boss"],
  "部下・同僚": ["coworker", "subordinate"],
  "面接": ["interview"],
  "医者": ["doctor"],
  "看護師": ["nurse"],
  "教師": ["teacher"],
  "インストラクター": ["instructor"],
  "ウェイトレス": ["waitress"],
  "メイド": ["maid"],
  "CA・スチュワーデス": ["cabin-attendant", "stewardess", "flight-attendant"],
  "受付嬢": ["receptionist"],
  "マッサージ": ["massage"],
  "エステ": ["aesthetic", "spa"],
  "病院・クリニック": ["hospital", "clinic"],
  "ホテル": ["hotel"],
  "温泉": ["onsen", "hot-spring"],
  "お風呂": ["bath"],
  "自宅": ["home"],
  "野外・屋外": ["outdoor", "outside"],
  "旅行": ["travel"],
  "デート": ["date"],
  "飲み会・合コン": ["party", "group-date"],
  "近所・ご近所": ["neighbor"],
  "カップル": ["couple"],
  "人妻": ["married-woman", "housewife"],
  "熟女": ["mature-woman", "milf"],
  "ママ友": ["mom-friend"],
  "姉・妹": ["sister"],
  "キャバ嬢・風俗嬢": ["hostess", "sex-worker"],
  "主婦": ["housewife"],
  "義母": ["stepmother"],
  "女教師": ["female-teacher"],
  "OL・職業色々": ["office-lady", "ol"],
  "女子大生": ["college-girl"],
  "お母さん": ["mom", "mother"],
  "女子校生": ["schoolgirl"],

  // ---- プレイ ----
  "キス": ["kiss"],
  "マッサージプレイ": ["massage-play"],
  "ロールプレイ": ["roleplay"],
  "おもちゃ": ["toy", "sex-toy"],
  "コスプレプレイ": ["cosplay-play"],
  "3P": ["3p", "threesome"],
  "複数プレイ": ["group-sex"],
  "シャワー": ["shower"],
  "ローション": ["lotion"],
  "オイル": ["oil"],
  "焦らし": ["tease", "edging"],
  "言葉責め": ["verbal", "dirty-talk"],
  "フェラ": ["blowjob"],
  "パイズリ": ["titjob"],
  "手コキ": ["handjob"],
  "クンニ": ["cunnilingus"],
  "オナニー": ["masturbation"],
  "シックスナイン": ["69"],
  "アナルセックス": ["anal"],
  "イマラチオ": ["deepthroat"],
  "イラマチオ": ["face-fuck"],
  "中出し": ["creampie"],
  "顔射": ["facial"],
  "縛り・緊縛": ["bondage", "shibari"],
  "騎乗位": ["cowgirl"],
  "潮吹き": ["squirting"],
  "放尿・お漏らし": ["pee", "pissing"],
  "飲尿": ["drinking-urine", "urine"],
  "羞恥": ["shame", "embarrassment"],
  "羞め": ["humiliation"],
  "4P": ["4p"],
  "デカチン・巨根": ["big-dick", "big-cock"],
  "電マ": ["vibrator", "denma"],
  "拘束": ["restraint"],
  "ぶっかけ": ["bukkake"],
  "パンチラ": ["panty-shot"],
  "胸チラ": ["cleavage-shot"],
  "スパンキング": ["spanking"],
  "カーセックス": ["car-sex"],
  "スカトロ": ["scat"],
  "ヨガ": ["yoga"],
  "オナサポ": ["masturbation-support"],

  // ---- その他 ----
  "VR": ["vr", "vr-only", "high-quality-vr"],
  "ハイクオリティVR": ["high-quality-vr"],
  "スマホ推奨": ["smartphone", "mobile"],
  "短尺": ["short", "short-video"],
  "4時間以上": ["4-hours", "over-4-hours"],
  "16時間以上": ["16-hours", "over-16-hours"],
  "シリーズ": ["series"],
  "セット商品": ["set", "bundle"],
  "デジモ": ["digimo"],
  "独占配信": ["exclusive"],
  "AI生成作品": ["ai", "ai-generated"],
  "FANZA配信限定": ["fanza-exclusive"],
  "4K": ["4k"],
  "3D": ["3d"],
  "VR専用": ["vr-only"],
  "縦動画": ["vertical", "vertical-video"],
};